.DEFAULT_GOAL := help
SHELL = /bin/bash

DOCKER_COMPOSE := docker-compose -f docker-compose.yml

.PHONY: default build start stop sh sh_root
default: help

symfony: ## install symfony application
	php infrastructure/scripts/composer.phar create-project symfony/website-skeleton application/hello-world

composer: ## install composer
	cd infrastructure/scripts && ./get-composer.sh

## MISC
help: ## This help dialog.
	@IFS=$$'\n' ; \
	help_lines=(`fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##/:/'`); \
	printf "%-30s %s\n" "Target" "Help" ; \
	printf "%-30s %s\n" "------" "----" ; \
	for help_line in $${help_lines[@]}; do \
		IFS=$$':' ; \
		help_split=($$help_line) ; \
		help_command=`echo $${help_split[0]} | sed -e 's/^ *//' -e 's/ *$$//'` ; \
		help_info=`echo $${help_split[2]} | sed -e 's/^ *//' -e 's/ *$$//'` ; \
		printf '\033[36m'; \
		printf "%-30s %s" $$help_command ; \
		printf '\033[0m'; \
		printf "%s\n" $$help_info; \
	done
